Blog app - integration specs for views and fix n+1 problems
Innocent259/blog-app pull request #10
Opened 2023-12-20 13:47 UTC by Innocent259

In this project milestone I: 

1. Fixed n+1 problem for fetching all posts and their comment of a user
2. Used Capybara to write integration tests of views

2023-12-20 14:26 UTC, Ibizugbe requested changes
Hi @Innocent259  @maths29 👋🏼👋🏼👋🏼, 

![request change](https://github.com/Innocent259/blog-app/assets/64643995/4f208fdb-efa1-457d-ab1c-beda2f592f84)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] `gitflow` is used👍🏼.
- [x] Tests for user index page has been written👍🏼.


## Required Changes ♻️

- [ ] In your PR, Kindly add a screenshot of your app's log before and after the fix and ensure all your tests are passing eb==before proceeding to request a review😉. as this is a requirement😉.
<img width="728" alt="image" src="https://github.com/Innocent259/blog-app/assets/64643995/9070180e-ce77-448c-84b6-4e0933dbb513">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-20 14:26 UTC, Ibizugbe commented on spec/features/users/show_spec.rb
> +    click_link 'See all posts'
Nice job so far😉. Just as [required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md) in the `user show page` kindly add the following tests😉.

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see the user's first 3 posts.
- When I click a user's post, it redirects me to that post's show page.
<img width="688" alt="image" src="https://github.com/Innocent259/blog-app/assets/64643995/8eefb723-1b0f-4d20-bbec-a5f645f4eab5">

2023-12-20 14:26 UTC, Ibizugbe commented on spec/features/posts/index_spec.rb
> +
Nice job so far, Just as [required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md), kindly do well to add the following tests😉.

- I can see a section for pagination if there are more posts than fit on the view.
- When I click on a post, it redirects me to that post's show page
<img width="727" alt="image" src="https://github.com/Innocent259/blog-app/assets/64643995/9b8ea959-ea67-40d1-98dc-0840550f577d">

2023-12-20 14:26 UTC, Ibizugbe commented on spec/features/posts/show_spec.rb
> +    end
Nice job so far👍🏼. you seem to have missed some tests here😉. Just as [required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md), kindly add the following tests👍🏼.

- I can see who wrote the post.
<img width="409" alt="image" src="https://github.com/Innocent259/blog-app/assets/64643995/32c10405-6a36-4a16-9f8e-af73eaa25239">

2023-12-21 09:10 UTC, OyePriscilla requested changes
Hi @Innocent259 👍, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Solved n+1 queries problem ✔️ 
Implemented some test cases as highlighted in previous review ✔️ 

 ## Required Changes ♻️

- [ ] Kindly add correct screenshot of the n+1 queries problem solved; the screenshot for before and after running the queries are the same. 👍 

<img width="602" alt="Untitled" src="https://github.com/Innocent259/blog-app/assets/103386183/1481c2b7-1b12-4b7c-99fb-578fd0af875a">

<img width="611" alt="Untitled" src="https://github.com/Innocent259/blog-app/assets/103386183/7fee3c97-f8bc-48f4-8b1c-24afea41e1f0">

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-21 09:10 UTC, OyePriscilla commented on spec/features/posts/index_spec.rb
> +end
- [ ] Please as requested earlier, kindly add this missing test that the previous reviewer highlighted. 👇 

<img width="417" alt="Untitled" src="https://github.com/Innocent259/blog-app/assets/103386183/fd6cb87b-46da-4ccd-a44e-a9c613070217">

2023-12-21 11:40 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Innocent259, and @maths29👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://github.com/Innocent259/blog-app/assets/83803414/13e8424b-74a9-43f7-9fcc-eaf4eef49b8e)

## To Highlight 🎉
- All tests are passed. ✔️ 
- Good job fixing n+1 problem. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-21 11:42 UTC, merged